"""empty message

Revision ID: ba113838e72b
Revises: 
Create Date: 2024-09-14 11:03:43.641907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba113838e72b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('deadline', sa.TIMESTAMP(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='statusevent'), nullable=False),
    sa.CheckConstraint('coefficient > 0', name='positive_number'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
