services:
  # База данных line-provider
  db_line-provider:
    image: postgres:13.8
    container_name: db_line-provider
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata_lp:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 30s
      retries: 5
      timeout: 5s
    profiles:
      - line-provider
      - both


  # Тестовая база данных
  test-database:
    image: postgres:13.8
    container_name: test-database_lp
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_HOST: ${POSTGRES_TEST_HOST}
    ports:
      - "${DB_TEST_PORT}:5432"
    volumes:
      - ./pgdata_tst_lp:/var/lib/postgresql/data  # Том для тестовой базы
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${TEST_POSTGRES_DB} -U ${TEST_POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      timeout: 5s
    profiles:
      - test
      - both
